### ISSUE TITLE
Unclosed connections

### ISSUE THREAD

**Issue by carloscabanero** [geraxe/dolib#19]
I am getting the following warning all the time when using the library:
`/usr/local/lib/python3.9/site-packages/httpx/_client.py:1914: UserWarning: Unclosed <httpx.AsyncClient object at 0x7f32118519d0>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.`

I may be missing something, but in case this is not handled or accommodated in some way, I would point at _rclient being initialized here, https://github.com/geraxe/dolib/blob/c28c190be6d8045e621c3eb046ff8c2764eddea9/dolib/client.py#L172, but never closed. With short lived apps this should not be an issue, but with long running applications like servers, the files will eventually fill out and the app will crash. 

I can fix this easily and contribute a PR but want to get your feedback on how you want me to proceed:
- We can close the _rclient on deinit.
- We can you an `async ... with` construction so that the object is automatically released after a block.

Given that _rclient is only used in very specific functions, I think the second option makes more sense. Let me know and I will submit a patch tomorrow as we need this from our side.

Thanks

**Comment by geraxe** [comment]
Hi Carlos!
Yes you are right. I don't understand why I used "_rclient". This looks a lot like a bug. Or hooks for something that didn't go into production. I think we just need to use "async with". 
I also saw another mistake - the use of blocking call "requests.get" inside the async client.

Thank you very much for paying attention to the problem. 

I think this PR will solve the problem )

**Comment by carloscabanero** [comment]
This is excellent. I didn’t notice the request.get issue myself, happy we got that one ironed out as well. Thank you!
